version: '1.0'

# docker run --name blog-mysql \
# -v ./blog-mysql/data:/var/lib/mysql \
# -v ./blog-mysql/config:/etc/mysql/conf.d \
# -v ./blog-mysql/initdb:/docker-entrypoint-initdb.d \
# -e TZ=Asia/Shanghai \
# -e MYSQL_ROOT_PASSWORD=123456 \
# --network blog-net \
# -d mysql

# docker build -t gg/blog:1.0 ./blog-back

# docker run --name blog-backend \
# -v ./blog-back/upload:/blog/upload \
# -v ./blog-back/application.yml:/blog/application.yml \
# -p 8081:8081 \
# --network blog-net \
# -d gg/blog:1.0

# docker run --name blog-front \
# -v ./blog-front/dist:/usr/share/nginx/html:ro \
# -v ./blog-front/nginx/nginx.conf:/etc/nginx/nginx.conf:ro \
# -p 81:81 \
# --network blog-net \
# -d nginx

services:
  blog-mysql:
    image: mysql
    container_name: blog-mysql
    ports:
      - 3306:3306
    volumes:
      - ./blog-mysql/data:/var/lib/mysql
      - ./blog-mysql/config:/etc/mysql/conf.d
      - ./blog-mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - blog-net
  blog-backend:
    build: 
      context: ./blog-back
      dockerfile: Dockerfile
    container_name: blog-backend
    ports:
      - 8081:8081
    volumes:
      - ./blog-back/upload:/blog/upload 
      - ./blog-back/application.yml:/blog/application.yml 
    networks:
      - blog-net
    depends_on:
      - blog-mysql
  blog-front:
    image: nginx
    container_name: blog-front
    ports:
      - 81:81
    volumes:
      - ./blog-front/dist:/usr/share/nginx/html:ro 
      - ./blog-front/nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
    networks:
      - blog-net
    depends_on:
      - blog-backend  

networks:
  blog-net: 
    name: blog-net