server:
  port: 8081
  servlet:
    context-path: /cms


spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 350MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blog-mysql:3306/cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd
    time-zone: Asia/Shanghai

uploadfilepath: /blog/upload/

logging:
  level:
    com:
      zhaoguoshun:
        mapper: debug

mybatis:
  type-aliases-package: com.hncu.entity
  mapper-locations:  classpath:mybatis/mapper/*.xml
pagehelper:
  helper-dialect: mysql
